@startuml AllClass

package Networks
{
    enum AccessPoint
    {
        NAME_LIST
        ROOM_ACCESS_LOG
    }

    class AccessPointData
    {
        +url: str
        +get_res_type: type
        +post_res_type: type
    }

    abstract DTO<<dataclass, dataclass_json>>
    {
        +from_json(json: str): DTO
    }

    class Network
    {
        +{static}is_connection(): bool
        +{static}get(access_point: AccessPoint, req: DTO): DTO
        +{static}post(access_point: AccessPoint, req: DTO): DTO
    }

    package Requests
    {
        enum Campus
        {
            OBASE,
            KOKURA
        }

        enum RoomAccessType
        {
            IN,
            OUT
        }

        class Discord 
        {
            +id: str
        }

        class Member 
        {
            +id: int
            +name: str
            +discord: Discord
        }

        class RoomAccessData 
        {
            member: Member
            campus: Campus
            type: RoomAccessType
        }

        class StudentID 
        {
            +id: int
        }
    }

    package Responses
    {
        class DiscordData 
        {
            +id: str
            +tag: str
            +nickname: str
        }

        class Game 
        {
            +title: str
            +id: str
        }

        class MemberData
        {
            +id: int
            +name: str
            +discord: DiscordData
            +games: List[Game]
        }

        class RoomAccessResult
        {
            state: str
            message: str
        }
    }
}

package SceneManagement
{
    class SceneManager
    {
        -__stack: list[Scene]
        -__currentScene: Scene
        +{class}load(scene: Scene): None
        +{class}back(): None
        +{class}back_root(): None
    }

    abstract Scene
    {
        -__backgound: PhotoImage
        +{abstract}on_load(): None
        +on_show(): None
        +on_hide(): None
        +on_destory(): None
    }

    package Scenes
    {
        abstract Announce
        {
            #_message: str
        }
        class Complete
        class Error
        class Home
        class Login
        {
            -__login_process(id: str): None
        }
        class Processing
        {
            -__task: Thread
        }
    }
}
package Systems
{
    class RoomAccessManager
    {
        +{static}access(id: str, access_type: RoomAccessType): 
    }
}
package Utils
{
    class ExtentionFunction
    {
        +{class}init(): None
        -__get_root_widget(): Misc
    }
}
package Widgets
{
    class BackButton
    abstract ImageButton
    {
        #{abstract}_on_click(): None
    }
    class RoomAccessButton
    {
        -__access_type: RoomAccessType
    }
}

tk.Frame --|> tk.Misc
tk.Button --|> tk.Misc

Scene --|> tk.Frame
Announce --|> Scene
Error --|> Scene
Home --|> Scene
Login --|> Scene
Processing --|> Scene
Complete --|> Scene
Error --|> Announce
Complete --|> Announce

RoomAccessData --|> DTO
StudentID --|> DTO
MemberData --|> DTO
DiscordData --|> DTO
Game --|> DTO
RoomAccessResult --|> DTO
Member --|> DTO
Discord --|> DTO

ImageButton --|> tk.Button
BackButton --|> ImageButton
RoomAccessButton --|> ImageButton

Network .left.> DTO
Network .up.> AccessPointData
AccessPoint .left.> AccessPointData
RoomAccessType .up.> RoomAccessData
Campus .up.> RoomAccessData

SceneManager "1" *.left.> "*" Scene

Game --+ MemberData
DiscordData --+ MemberData
Member --+ RoomAccessData
Discord --+ Member

Login --> RoomAccessManager : use
RoomAccessManager --> Network : use
ExtentionFunction --> tk.Misc : extention

@enduml